# Numpy Assignment

## 1. Import Libraries
Import the `numpy` library to get started.

In [1]:
import numpy as np

## 2. Array Creation
Create a numpy array containing integers from 1 to 20 using `arange`.

In [2]:
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

## 3. Basic Statistics
Calculate the sum, mean, median, and standard deviation of the array elements.

In [3]:
print("Sum of array",np.sum(arr))
print("Mean of array",np.mean(arr))
print("Median",np.median(arr))
print("standard deviation of array",np.std(arr))

Sum of array 210
Mean of array 10.5
Median 10.5
standard deviation of array 5.766281297335398


## 4. Conditional Selection
Select elements greater than 10 and find their indices.

In [4]:
print("element greater than 10", arr[arr > 10])
print("Indices of element greater than 10",np.where(arr > 10)[0])

element greater than 10 [11 12 13 14 15 16 17 18 19 20]
Indices of element greater than 10 [10 11 12 13 14 15 16 17 18 19]


## 5. Reshaping Arrays
Create a new array with values 1 to 16 and reshape it into a 4x4 matrix.

In [5]:
arr_4 = np.reshape(np.arange(1, 17), (4, 4))
print("4 * 4 array of range 1 to 16",arr_4)

4 * 4 array of range 1 to 16 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## 6. Transpose
Find the transpose of the 4x4 array.

In [6]:
print("Transpose of array",np.transpose(arr_4))

Transpose of array [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


## 7. Summation along Axes
Calculate the sum of elements along rows (axis 0) and columns (axis 1).

In [7]:
print("Sum of rows :", np.sum(arr_4, 0))
print("Sum of Column :", np.sum(arr_4, 1))

Sum of rows : [28 32 36 40]
Sum of Column : [10 26 42 58]


## 8. Random Array Generation
Generate two 3x3 arrays with random integers between 1 and 20.

In [8]:
arr1 = np.random.randint(1, 21, (3, 3))
arr2 = np.random.randint(1, 21, (3, 3))
print("arr1 : \n", arr1)
print("arr2 : \n", arr2)

arr1 : 
 [[17 20 11]
 [ 5  2  2]
 [ 1  2  7]]
arr2 : 
 [[10  2  2]
 [ 6  7 14]
 [ 3 10  3]]


## 9. Element-wise Arithmetic
Perform addition, subtraction, and multiplication on the two random arrays.

In [9]:
print("Addition\n",arr1 + arr2)
print("Subtraction\n",arr1 - arr2)
print("Multiplication\n",arr1 * arr2)

Addition
 [[27 22 13]
 [11  9 16]
 [ 4 12 10]]
Subtraction
 [[  7  18   9]
 [ -1  -5 -12]
 [ -2  -8   4]]
Multiplication
 [[170  40  22]
 [ 30  14  28]
 [  3  20  21]]


## 10. Matrix Multiplication
Calculate the dot product of the two arrays.

In [10]:
print("Dot product of arr1 and arr2",np.dot(arr1, arr2))

Dot product of arr1 and arr2 [[323 284 347]
 [ 68  44  44]
 [ 43  86  51]]


## 11. Custom Array Reshaping
Create a 1D array with specific values and reshape it into a 3x4 matrix.

In [11]:
arr_1d = np.array([18, 23, 34 ,56, 43, 78, 87, 45, 67, 16, 31, 94])
arr_2d = np.reshape(arr_1d, (3, 4))
print(arr_2d)

[[18 23 34 56]
 [43 78 87 45]
 [67 16 31 94]]


## 12. Array Slicing
Extract a sub-array from the 3x4 matrix (first two rows, last two columns).

In [12]:
print(arr_2d[0 : 2, 2 : 4])

[[34 56]
 [87 45]]
